[features]
seeds = false
skip-lint = false
[programs.localnet]
game = "3L9CnAEGvcy3zhToKb3W3frSgRJrnzfEftczEX7AUtMQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
